name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "senrea.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.senrea.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.senrea.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.senrea.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.senrea.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.senrea.biz.id", custom_domain = true },  
  { pattern = "cache.netflix.com.senrea.biz.id", custom_domain = true },
  { pattern = "investor.fb.com.senrea.biz.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "0e106e0e849c4f4f98b3d86b1121163d"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/lekyah/inconigto-vpn/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/lekyah/inconigto-vpn/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/lekyah/inconigto-vpn/refs/heads/master/web/link.html"
